spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:sqlserver://localhost\MSSQLSERVER:1433;database=Order;encrypt=true;trustServerCertificate=true;
    username: order
    password: pass
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher
server:
  port: 8080